package androidx.compose.material3.tokens;

/* JADX INFO: compiled from: r8-map-id-e67002de5a40c891c754bff9e68f2bf8edbc7d2191d59a60e5e311fc3b432df9 */
/* JADX INFO: loaded from: classes.dex */
public abstract class b0 {
    public static final long A;
    public static final long A0;
    public static final androidx.compose.ui.text.font.m A1;
    public static final long B;
    public static final androidx.compose.ui.text.font.k B0;
    public static final long B1;
    public static final long C;
    public static final androidx.compose.ui.text.font.m C0;
    public static final long C1;
    public static final androidx.compose.ui.text.font.k D;
    public static final long D0;
    public static final long D1;
    public static final androidx.compose.ui.text.font.m E;
    public static final long E0;
    public static final androidx.compose.ui.text.font.k E1;
    public static final long F;
    public static final long F0;
    public static final androidx.compose.ui.text.font.m F1;
    public static final long G;
    public static final androidx.compose.ui.text.font.k G0;
    public static final long G1;
    public static final long H;
    public static final androidx.compose.ui.text.font.m H0;
    public static final long H1;
    public static final androidx.compose.ui.text.font.k I;
    public static final long I0;
    public static final long I1;
    public static final androidx.compose.ui.text.font.m J;
    public static final long J0;
    public static final androidx.compose.ui.text.font.k J1;
    public static final long K;
    public static final long K0;
    public static final androidx.compose.ui.text.font.m K1;
    public static final long L;
    public static final androidx.compose.ui.text.font.k L0;
    public static final long L1;
    public static final long M;
    public static final androidx.compose.ui.text.font.m M0;
    public static final long M1;
    public static final androidx.compose.ui.text.font.k N;
    public static final long N0;
    public static final long N1;
    public static final androidx.compose.ui.text.font.m O;
    public static final long O0;
    public static final androidx.compose.ui.text.font.k O1;
    public static final long P;
    public static final long P0;
    public static final androidx.compose.ui.text.font.m P1;
    public static final long Q;
    public static final androidx.compose.ui.text.font.k Q0;
    public static final long Q1;
    public static final long R;
    public static final androidx.compose.ui.text.font.m R0;
    public static final long R1;
    public static final androidx.compose.ui.text.font.k S;
    public static final long S0;
    public static final long S1;
    public static final androidx.compose.ui.text.font.m T;
    public static final long T0;
    public static final androidx.compose.ui.text.font.k T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final androidx.compose.ui.text.font.k V0;
    public static final long W;
    public static final androidx.compose.ui.text.font.m W0;
    public static final androidx.compose.ui.text.font.k X;
    public static final long X0;
    public static final androidx.compose.ui.text.font.m Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final androidx.compose.ui.text.font.m a;
    public static final long a0;
    public static final androidx.compose.ui.text.font.k a1;
    public static final long b;
    public static final long b0;
    public static final androidx.compose.ui.text.font.m b1;
    public static final long c;
    public static final androidx.compose.ui.text.font.k c0;
    public static final long c1;
    public static final long d;
    public static final androidx.compose.ui.text.font.m d0;
    public static final long d1;
    public static final androidx.compose.ui.text.font.k e;
    public static final long e0;
    public static final long e1;
    public static final androidx.compose.ui.text.font.m f;
    public static final long f0;
    public static final androidx.compose.ui.text.font.k f1;
    public static final long g;
    public static final long g0;
    public static final androidx.compose.ui.text.font.m g1;
    public static final long h;
    public static final androidx.compose.ui.text.font.k h0;
    public static final long h1;
    public static final long i;
    public static final androidx.compose.ui.text.font.m i0;
    public static final long i1;
    public static final androidx.compose.ui.text.font.k j;
    public static final long j0;
    public static final long j1;
    public static final androidx.compose.ui.text.font.m k;
    public static final long k0;
    public static final androidx.compose.ui.text.font.k k1;
    public static final long l;
    public static final long l0;
    public static final androidx.compose.ui.text.font.m l1;
    public static final long m;
    public static final androidx.compose.ui.text.font.k m0;
    public static final long m1;
    public static final long n;
    public static final androidx.compose.ui.text.font.m n0;
    public static final long n1;
    public static final androidx.compose.ui.text.font.k o;
    public static final long o0;
    public static final long o1;
    public static final androidx.compose.ui.text.font.m p;
    public static final long p0;
    public static final androidx.compose.ui.text.font.k p1;
    public static final long q;
    public static final long q0;
    public static final androidx.compose.ui.text.font.m q1;
    public static final long r;
    public static final androidx.compose.ui.text.font.k r0;
    public static final long r1;
    public static final long s;
    public static final androidx.compose.ui.text.font.m s0;
    public static final long s1;
    public static final androidx.compose.ui.text.font.k t;
    public static final long t0;
    public static final long t1;
    public static final androidx.compose.ui.text.font.m u;
    public static final long u0;
    public static final androidx.compose.ui.text.font.k u1;
    public static final long v;
    public static final long v0;
    public static final androidx.compose.ui.text.font.m v1;
    public static final long w;
    public static final androidx.compose.ui.text.font.k w0;
    public static final long w1;
    public static final long x;
    public static final androidx.compose.ui.text.font.m x0;
    public static final long x1;
    public static final androidx.compose.ui.text.font.k y;
    public static final long y0;
    public static final long y1;
    public static final androidx.compose.ui.text.font.m z;
    public static final long z0;
    public static final androidx.compose.ui.text.font.k z1;

    static {
        androidx.compose.ui.text.font.k kVar = c0.a;
        androidx.compose.ui.text.font.m mVar = androidx.compose.ui.text.font.r.b;
        a = mVar;
        b = coil3.svg.internal.a.w(24.0d);
        c = coil3.svg.internal.a.x(16);
        d = coil3.svg.internal.a.w(0.5d);
        androidx.compose.ui.text.font.k kVar2 = c0.c;
        e = kVar2;
        f = mVar;
        g = coil3.svg.internal.a.w(20.0d);
        h = coil3.svg.internal.a.x(14);
        i = coil3.svg.internal.a.w(0.2d);
        j = kVar2;
        k = mVar;
        l = coil3.svg.internal.a.w(16.0d);
        m = coil3.svg.internal.a.x(12);
        n = coil3.svg.internal.a.w(0.4d);
        o = kVar2;
        p = mVar;
        q = coil3.svg.internal.a.w(64.0d);
        r = coil3.svg.internal.a.x(57);
        long jW = coil3.svg.internal.a.w(0.2d);
        androidx.compose.ui.unit.p[] pVarArr = androidx.compose.ui.unit.o.b;
        long j2 = jW & 1095216660480L;
        if (j2 == 0) {
            androidx.compose.ui.unit.i.a("Cannot perform operation for Unspecified type.");
        }
        s = coil3.svg.internal.a.H(-androidx.compose.ui.unit.o.c(jW), j2);
        t = kVar2;
        u = mVar;
        v = coil3.svg.internal.a.w(52.0d);
        w = coil3.svg.internal.a.x(45);
        x = coil3.svg.internal.a.w(0.0d);
        y = kVar2;
        z = mVar;
        A = coil3.svg.internal.a.w(44.0d);
        B = coil3.svg.internal.a.x(36);
        C = coil3.svg.internal.a.w(0.0d);
        D = kVar2;
        E = mVar;
        F = coil3.svg.internal.a.w(40.0d);
        G = coil3.svg.internal.a.x(32);
        H = coil3.svg.internal.a.w(0.0d);
        I = kVar2;
        J = mVar;
        K = coil3.svg.internal.a.w(36.0d);
        L = coil3.svg.internal.a.x(28);
        M = coil3.svg.internal.a.w(0.0d);
        N = kVar2;
        O = mVar;
        P = coil3.svg.internal.a.w(32.0d);
        Q = coil3.svg.internal.a.x(24);
        R = coil3.svg.internal.a.w(0.0d);
        S = kVar2;
        T = mVar;
        U = coil3.svg.internal.a.w(20.0d);
        V = coil3.svg.internal.a.x(14);
        W = coil3.svg.internal.a.w(0.1d);
        androidx.compose.ui.text.font.k kVar3 = c0.b;
        X = kVar3;
        Y = mVar;
        Z = coil3.svg.internal.a.w(16.0d);
        a0 = coil3.svg.internal.a.x(12);
        b0 = coil3.svg.internal.a.w(0.5d);
        c0 = kVar3;
        d0 = mVar;
        e0 = coil3.svg.internal.a.w(16.0d);
        f0 = coil3.svg.internal.a.x(11);
        g0 = coil3.svg.internal.a.w(0.5d);
        h0 = kVar3;
        i0 = mVar;
        j0 = coil3.svg.internal.a.w(28.0d);
        k0 = coil3.svg.internal.a.x(22);
        l0 = coil3.svg.internal.a.w(0.0d);
        m0 = kVar2;
        n0 = mVar;
        o0 = coil3.svg.internal.a.w(24.0d);
        p0 = coil3.svg.internal.a.x(16);
        q0 = coil3.svg.internal.a.w(0.2d);
        r0 = kVar3;
        s0 = mVar;
        t0 = coil3.svg.internal.a.w(20.0d);
        u0 = coil3.svg.internal.a.x(14);
        v0 = coil3.svg.internal.a.w(0.1d);
        w0 = kVar3;
        x0 = mVar;
        y0 = coil3.svg.internal.a.w(24.0d);
        z0 = coil3.svg.internal.a.x(16);
        A0 = coil3.svg.internal.a.w(0.15d);
        B0 = kVar3;
        C0 = mVar;
        D0 = coil3.svg.internal.a.w(20.0d);
        E0 = coil3.svg.internal.a.x(14);
        F0 = coil3.svg.internal.a.w(0.25d);
        G0 = kVar3;
        H0 = mVar;
        I0 = coil3.svg.internal.a.w(16.0d);
        J0 = coil3.svg.internal.a.x(12);
        K0 = coil3.svg.internal.a.w(0.4d);
        L0 = kVar3;
        M0 = mVar;
        N0 = coil3.svg.internal.a.w(64.0d);
        O0 = coil3.svg.internal.a.x(57);
        P0 = coil3.svg.internal.a.x(0);
        Q0 = kVar3;
        R0 = mVar;
        S0 = coil3.svg.internal.a.w(52.0d);
        T0 = coil3.svg.internal.a.x(45);
        U0 = coil3.svg.internal.a.x(0);
        V0 = kVar3;
        W0 = mVar;
        X0 = coil3.svg.internal.a.w(44.0d);
        Y0 = coil3.svg.internal.a.x(36);
        Z0 = coil3.svg.internal.a.x(0);
        a1 = kVar3;
        b1 = mVar;
        c1 = coil3.svg.internal.a.w(40.0d);
        d1 = coil3.svg.internal.a.x(32);
        e1 = coil3.svg.internal.a.x(0);
        f1 = kVar3;
        g1 = mVar;
        h1 = coil3.svg.internal.a.w(36.0d);
        i1 = coil3.svg.internal.a.x(28);
        j1 = coil3.svg.internal.a.x(0);
        k1 = kVar3;
        l1 = mVar;
        m1 = coil3.svg.internal.a.w(32.0d);
        n1 = coil3.svg.internal.a.x(24);
        o1 = coil3.svg.internal.a.x(0);
        p1 = kVar3;
        q1 = mVar;
        r1 = coil3.svg.internal.a.w(20.0d);
        s1 = coil3.svg.internal.a.x(14);
        t1 = coil3.svg.internal.a.w(0.1d);
        androidx.compose.ui.text.font.k kVar4 = c0.a;
        u1 = kVar4;
        v1 = mVar;
        w1 = coil3.svg.internal.a.w(16.0d);
        x1 = coil3.svg.internal.a.x(12);
        y1 = coil3.svg.internal.a.w(0.5d);
        z1 = kVar4;
        A1 = mVar;
        B1 = coil3.svg.internal.a.w(16.0d);
        C1 = coil3.svg.internal.a.x(11);
        D1 = coil3.svg.internal.a.w(0.5d);
        E1 = kVar4;
        F1 = mVar;
        G1 = coil3.svg.internal.a.w(28.0d);
        H1 = coil3.svg.internal.a.x(22);
        I1 = coil3.svg.internal.a.x(0);
        J1 = kVar3;
        K1 = mVar;
        L1 = coil3.svg.internal.a.w(24.0d);
        M1 = coil3.svg.internal.a.x(16);
        N1 = coil3.svg.internal.a.w(0.15d);
        O1 = kVar4;
        P1 = mVar;
        Q1 = coil3.svg.internal.a.w(20.0d);
        R1 = coil3.svg.internal.a.x(14);
        S1 = coil3.svg.internal.a.w(0.1d);
        T1 = kVar4;
    }
}
