package androidx.compose.material3.tokens;

/* JADX INFO: compiled from: r8-map-id-e67002de5a40c891c754bff9e68f2bf8edbc7d2191d59a60e5e311fc3b432df9 */
/* JADX INFO: loaded from: classes.dex */
public abstract class e {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = u.r;
        a = j2;
        b = u.d;
        c = u.e;
        d = u.p;
        long j3 = u.A;
        e = j3;
        f = u.i;
        long j4 = u.g;
        g = j4;
        h = u.b;
        i = u.a;
        j = u.x;
        long j5 = u.w;
        k = j5;
        l = j5;
        m = u.y;
        n = u.D;
        long j6 = u.C;
        o = j6;
        p = j6;
        q = u.E;
        r = j4;
        s = u.s;
        t = u.J;
        long j7 = u.I;
        u = j7;
        v = j7;
        w = u.K;
        x = u.t;
        y = u.u;
        z = u.z;
        long j8 = u.B;
        A = j8;
        B = j8;
        C = j3;
        D = u.f;
        E = u.F;
        long j9 = u.H;
        F = j9;
        G = j9;
        H = u.G;
        I = j2;
        J = j2;
        K = u.o;
        L = u.n;
        M = u.m;
        N = u.q;
        O = u.h;
        P = u.l;
        Q = u.v;
        R = u.L;
        long j10 = u.N;
        S = j10;
        T = j10;
        U = u.M;
    }
}
