package androidx.compose.material3.tokens;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public abstract class e {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = s.r;
        a = j2;
        b = s.d;
        c = s.e;
        d = s.p;
        long j3 = s.A;
        e = j3;
        f = s.i;
        long j4 = s.g;
        g = j4;
        h = s.b;
        i = s.a;
        j = s.x;
        long j5 = s.w;
        k = j5;
        l = j5;
        m = s.y;
        n = s.D;
        long j6 = s.C;
        o = j6;
        p = j6;
        q = s.E;
        r = j4;
        s = s.s;
        t = s.J;
        long j7 = s.I;
        u = j7;
        v = j7;
        w = s.K;
        x = s.t;
        y = s.u;
        z = s.z;
        long j8 = s.B;
        A = j8;
        B = j8;
        C = j3;
        D = s.f;
        E = s.F;
        long j9 = s.H;
        F = j9;
        G = j9;
        H = s.G;
        I = j2;
        J = j2;
        K = s.o;
        L = s.n;
        M = s.m;
        N = s.q;
        O = s.h;
        P = s.l;
        Q = s.v;
        R = s.L;
        long j10 = s.N;
        S = j10;
        T = j10;
        U = s.M;
    }
}
