package androidx.compose.material3.tokens;

import com.app.mlounge.emulator.LibretroCore;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Token;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public abstract class s {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final /* synthetic */ int O = 0;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        androidx.compose.ui.graphics.a0.e(0, 0, 0);
        androidx.compose.ui.graphics.a0.e(0, 0, 0);
        a = androidx.compose.ui.graphics.a0.e(65, 14, 11);
        b = androidx.compose.ui.graphics.a0.e(255, 255, 255);
        androidx.compose.ui.graphics.a0.e(96, 20, 16);
        c = androidx.compose.ui.graphics.a0.e(140, 29, 24);
        d = androidx.compose.ui.graphics.a0.e(Token.YIELD_STAR, 38, 30);
        androidx.compose.ui.graphics.a0.e(220, 54, 46);
        androidx.compose.ui.graphics.a0.e(228, Token.ASSIGN_LSH, 98);
        androidx.compose.ui.graphics.a0.e(236, Token.LOOP, Token.COMPUTED_PROPERTY);
        androidx.compose.ui.graphics.a0.e(242, Token.DOTDOTDOT, Token.TEMPLATE_CHARS);
        e = androidx.compose.ui.graphics.a0.e(249, 222, 220);
        androidx.compose.ui.graphics.a0.e(252, 238, 238);
        androidx.compose.ui.graphics.a0.e(255, 251, 249);
        f = androidx.compose.ui.graphics.a0.e(0, 0, 0);
        g = androidx.compose.ui.graphics.a0.e(29, 27, 32);
        h = androidx.compose.ui.graphics.a0.e(255, 255, 255);
        androidx.compose.ui.graphics.a0.e(33, 31, 38);
        androidx.compose.ui.graphics.a0.e(43, 41, 48);
        i = androidx.compose.ui.graphics.a0.e(50, 47, 53);
        androidx.compose.ui.graphics.a0.e(54, 52, 59);
        j = androidx.compose.ui.graphics.a0.e(59, 56, 62);
        androidx.compose.ui.graphics.a0.e(72, 70, 76);
        androidx.compose.ui.graphics.a0.e(15, 13, 19);
        androidx.compose.ui.graphics.a0.e(96, 93, 100);
        androidx.compose.ui.graphics.a0.e(Token.DOT, Token.AND, Token.IF);
        k = androidx.compose.ui.graphics.a0.e(20, 18, 24);
        androidx.compose.ui.graphics.a0.e(Token.EXPR_VOID, Token.BLOCK, 150);
        androidx.compose.ui.graphics.a0.e(Token.DEBUGGER, Token.SETCONST, Token.METHOD);
        androidx.compose.ui.graphics.a0.e(202, 197, 205);
        l = androidx.compose.ui.graphics.a0.e(222, 216, 225);
        m = androidx.compose.ui.graphics.a0.e(230, LibretroCore.SCREEN_HEIGHT, 233);
        n = androidx.compose.ui.graphics.a0.e(236, 230, 240);
        o = androidx.compose.ui.graphics.a0.e(243, 237, 247);
        p = androidx.compose.ui.graphics.a0.e(245, 239, 247);
        q = androidx.compose.ui.graphics.a0.e(247, 242, Context.VERSION_ECMASCRIPT);
        r = androidx.compose.ui.graphics.a0.e(254, 247, 255);
        androidx.compose.ui.graphics.a0.e(255, 251, 255);
        androidx.compose.ui.graphics.a0.e(0, 0, 0);
        androidx.compose.ui.graphics.a0.e(29, 26, 34);
        androidx.compose.ui.graphics.a0.e(255, 255, 255);
        androidx.compose.ui.graphics.a0.e(50, 47, 55);
        s = androidx.compose.ui.graphics.a0.e(73, 69, 79);
        androidx.compose.ui.graphics.a0.e(96, 93, Token.ASSIGN_BITXOR);
        t = androidx.compose.ui.graphics.a0.e(Token.DOT, Token.COLON, Token.ELSE);
        androidx.compose.ui.graphics.a0.e(Token.EXPR_VOID, Token.BLOCK, Token.SETPROP_OP);
        androidx.compose.ui.graphics.a0.e(Token.DEBUGGER, Token.SETCONST, 180);
        u = androidx.compose.ui.graphics.a0.e(202, 196, 208);
        v = androidx.compose.ui.graphics.a0.e(231, LibretroCore.SCREEN_HEIGHT, 236);
        androidx.compose.ui.graphics.a0.e(245, 238, Context.VERSION_ECMASCRIPT);
        androidx.compose.ui.graphics.a0.e(255, 251, 254);
        androidx.compose.ui.graphics.a0.e(0, 0, 0);
        w = androidx.compose.ui.graphics.a0.e(33, 0, 93);
        x = androidx.compose.ui.graphics.a0.e(255, 255, 255);
        androidx.compose.ui.graphics.a0.e(56, 30, 114);
        y = androidx.compose.ui.graphics.a0.e(79, 55, Token.VOID);
        z = androidx.compose.ui.graphics.a0.e(Token.ASSIGN_BITAND, 80, Token.TO_DOUBLE);
        androidx.compose.ui.graphics.a0.e(127, Token.ASSIGN_BITAND, 190);
        androidx.compose.ui.graphics.a0.e(Token.SETELEM_OP, 130, 219);
        androidx.compose.ui.graphics.a0.e(Token.TEMPLATE_LITERAL_SUBST, Token.DOTDOT, 248);
        A = androidx.compose.ui.graphics.a0.e(208, 188, 255);
        B = androidx.compose.ui.graphics.a0.e(234, 221, 255);
        androidx.compose.ui.graphics.a0.e(246, 237, 255);
        androidx.compose.ui.graphics.a0.e(255, 251, 254);
        androidx.compose.ui.graphics.a0.e(0, 0, 0);
        C = androidx.compose.ui.graphics.a0.e(29, 25, 43);
        D = androidx.compose.ui.graphics.a0.e(255, 255, 255);
        androidx.compose.ui.graphics.a0.e(51, 45, 65);
        E = androidx.compose.ui.graphics.a0.e(74, 68, 88);
        F = androidx.compose.ui.graphics.a0.e(98, 91, Token.ASSIGN_EXP);
        androidx.compose.ui.graphics.a0.e(Token.FUNCTION, 114, Token.CATCH);
        androidx.compose.ui.graphics.a0.e(Token.JSR, Token.EMPTY, Token.GET);
        androidx.compose.ui.graphics.a0.e(Token.GENEXPR, Token.LET, 192);
        G = androidx.compose.ui.graphics.a0.e(204, 194, 220);
        H = androidx.compose.ui.graphics.a0.e(232, 222, 248);
        androidx.compose.ui.graphics.a0.e(246, 237, 255);
        androidx.compose.ui.graphics.a0.e(255, 251, 254);
        androidx.compose.ui.graphics.a0.e(0, 0, 0);
        I = androidx.compose.ui.graphics.a0.e(49, 17, 29);
        J = androidx.compose.ui.graphics.a0.e(255, 255, 255);
        androidx.compose.ui.graphics.a0.e(73, 37, 50);
        K = androidx.compose.ui.graphics.a0.e(99, 59, 72);
        L = androidx.compose.ui.graphics.a0.e(Token.IF, 82, 96);
        androidx.compose.ui.graphics.a0.e(Token.USE_STACK, Token.ASSIGN_LSH, Token.INC);
        androidx.compose.ui.graphics.a0.e(Token.TEMPLATE_CHARS, Token.DO, Token.LOOP);
        androidx.compose.ui.graphics.a0.e(210, Token.DOTDOT, Token.LETEXPR);
        M = androidx.compose.ui.graphics.a0.e(239, Token.DOTDOTDOT, Context.VERSION_ES6);
        N = androidx.compose.ui.graphics.a0.e(255, 216, 228);
        androidx.compose.ui.graphics.a0.e(255, 236, 241);
        androidx.compose.ui.graphics.a0.e(255, 251, Context.VERSION_ECMASCRIPT);
        androidx.compose.ui.graphics.a0.e(255, 255, 255);
    }
}
