package androidx.compose.material3.tokens;

/* JADX INFO: compiled from: r8-map-id-e67002de5a40c891c754bff9e68f2bf8edbc7d2191d59a60e5e311fc3b432df9 */
/* JADX INFO: loaded from: classes.dex */
public abstract class t {
    public static final f A;
    public static final f B;
    public static final f C;
    public static final f D;
    public static final f E;
    public static final f F;
    public static final f G;
    public static final f H;
    public static final w I;
    public static final f J;
    public static final d0 K;
    public static final f L;
    public static final f M;
    public static final f N;
    public static final f O;
    public static final float P;
    public static final float Q = 0.38f;
    public static final f a;
    public static final float b;
    public static final f c;
    public static final f d;
    public static final w e;
    public static final f f;
    public static final f g;
    public static final f h;
    public static final f i;
    public static final f j;
    public static final f k;
    public static final f l;
    public static final f m;
    public static final f n;
    public static final f o;
    public static final f p;
    public static final f q;
    public static final f r;
    public static final f s;
    public static final f t;
    public static final f u;
    public static final f v;
    public static final f w;
    public static final f x;
    public static final f y;
    public static final f z;

    static {
        f fVar = f.E;
        a = fVar;
        b = 0.38f;
        c = fVar;
        f fVar2 = f.H;
        d = fVar2;
        e = w.z;
        f fVar3 = f.D;
        f = fVar3;
        g = fVar3;
        h = fVar3;
        i = fVar3;
        j = fVar3;
        k = fVar3;
        f fVar4 = f.e;
        l = fVar4;
        m = fVar3;
        n = fVar4;
        f fVar5 = f.E;
        o = fVar5;
        p = fVar4;
        q = fVar4;
        r = fVar4;
        s = fVar3;
        t = fVar2;
        u = fVar5;
        v = fVar2;
        w = fVar5;
        x = fVar5;
        y = fVar3;
        z = fVar5;
        A = fVar5;
        B = fVar5;
        C = fVar5;
        D = fVar5;
        E = f.F;
        F = fVar5;
        G = fVar5;
        H = f.z;
        I = w.z;
        J = f.y;
        K = d0.z;
        L = f.H;
        M = f.K;
        N = f.I;
        O = f.E;
        P = 0.38f;
    }
}
