package androidx.compose.material3.tokens;

import androidx.datastore.preferences.protobuf.h1;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public abstract class y {
    public static final long A;
    public static final long A0;
    public static final androidx.compose.ui.text.font.n A1;
    public static final long B;
    public static final androidx.compose.ui.text.font.l B0;
    public static final long B1;
    public static final long C;
    public static final androidx.compose.ui.text.font.n C0;
    public static final long C1;
    public static final androidx.compose.ui.text.font.l D;
    public static final long D0;
    public static final long D1;
    public static final androidx.compose.ui.text.font.n E;
    public static final long E0;
    public static final androidx.compose.ui.text.font.l E1;
    public static final long F;
    public static final long F0;
    public static final androidx.compose.ui.text.font.n F1;
    public static final long G;
    public static final androidx.compose.ui.text.font.l G0;
    public static final long G1;
    public static final long H;
    public static final androidx.compose.ui.text.font.n H0;
    public static final long H1;
    public static final androidx.compose.ui.text.font.l I;
    public static final long I0;
    public static final long I1;
    public static final androidx.compose.ui.text.font.n J;
    public static final long J0;
    public static final androidx.compose.ui.text.font.l J1;
    public static final long K;
    public static final long K0;
    public static final androidx.compose.ui.text.font.n K1;
    public static final long L;
    public static final androidx.compose.ui.text.font.l L0;
    public static final long L1;
    public static final long M;
    public static final androidx.compose.ui.text.font.n M0;
    public static final long M1;
    public static final androidx.compose.ui.text.font.l N;
    public static final long N0;
    public static final long N1;
    public static final androidx.compose.ui.text.font.n O;
    public static final long O0;
    public static final androidx.compose.ui.text.font.l O1;
    public static final long P;
    public static final long P0;
    public static final androidx.compose.ui.text.font.n P1;
    public static final long Q;
    public static final androidx.compose.ui.text.font.l Q0;
    public static final long Q1;
    public static final long R;
    public static final androidx.compose.ui.text.font.n R0;
    public static final long R1;
    public static final androidx.compose.ui.text.font.l S;
    public static final long S0;
    public static final long S1;
    public static final androidx.compose.ui.text.font.n T;
    public static final long T0;
    public static final androidx.compose.ui.text.font.l T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final androidx.compose.ui.text.font.l V0;
    public static final long W;
    public static final androidx.compose.ui.text.font.n W0;
    public static final androidx.compose.ui.text.font.l X;
    public static final long X0;
    public static final androidx.compose.ui.text.font.n Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final androidx.compose.ui.text.font.n a;
    public static final long a0;
    public static final androidx.compose.ui.text.font.l a1;
    public static final long b;
    public static final long b0;
    public static final androidx.compose.ui.text.font.n b1;
    public static final long c;
    public static final androidx.compose.ui.text.font.l c0;
    public static final long c1;
    public static final long d;
    public static final androidx.compose.ui.text.font.n d0;
    public static final long d1;
    public static final androidx.compose.ui.text.font.l e;
    public static final long e0;
    public static final long e1;
    public static final androidx.compose.ui.text.font.n f;
    public static final long f0;
    public static final androidx.compose.ui.text.font.l f1;
    public static final long g;
    public static final long g0;
    public static final androidx.compose.ui.text.font.n g1;
    public static final long h;
    public static final androidx.compose.ui.text.font.l h0;
    public static final long h1;
    public static final long i;
    public static final androidx.compose.ui.text.font.n i0;
    public static final long i1;
    public static final androidx.compose.ui.text.font.l j;
    public static final long j0;
    public static final long j1;
    public static final androidx.compose.ui.text.font.n k;
    public static final long k0;
    public static final androidx.compose.ui.text.font.l k1;
    public static final long l;
    public static final long l0;
    public static final androidx.compose.ui.text.font.n l1;
    public static final long m;
    public static final androidx.compose.ui.text.font.l m0;
    public static final long m1;
    public static final long n;
    public static final androidx.compose.ui.text.font.n n0;
    public static final long n1;
    public static final androidx.compose.ui.text.font.l o;
    public static final long o0;
    public static final long o1;
    public static final androidx.compose.ui.text.font.n p;
    public static final long p0;
    public static final androidx.compose.ui.text.font.l p1;
    public static final long q;
    public static final long q0;
    public static final androidx.compose.ui.text.font.n q1;
    public static final long r;
    public static final androidx.compose.ui.text.font.l r0;
    public static final long r1;
    public static final long s;
    public static final androidx.compose.ui.text.font.n s0;
    public static final long s1;
    public static final androidx.compose.ui.text.font.l t;
    public static final long t0;
    public static final long t1;
    public static final androidx.compose.ui.text.font.n u;
    public static final long u0;
    public static final androidx.compose.ui.text.font.l u1;
    public static final long v;
    public static final long v0;
    public static final androidx.compose.ui.text.font.n v1;
    public static final long w;
    public static final androidx.compose.ui.text.font.l w0;
    public static final long w1;
    public static final long x;
    public static final androidx.compose.ui.text.font.n x0;
    public static final long x1;
    public static final androidx.compose.ui.text.font.l y;
    public static final long y0;
    public static final long y1;
    public static final androidx.compose.ui.text.font.n z;
    public static final long z0;
    public static final androidx.compose.ui.text.font.l z1;

    static {
        androidx.compose.ui.text.font.l lVar = z.a;
        androidx.compose.ui.text.font.n nVar = androidx.compose.ui.text.font.s.b;
        a = nVar;
        b = h1.q(24.0d);
        c = h1.r(16);
        d = h1.q(0.5d);
        androidx.compose.ui.text.font.l lVar2 = z.c;
        e = lVar2;
        f = nVar;
        g = h1.q(20.0d);
        h = h1.r(14);
        i = h1.q(0.2d);
        j = lVar2;
        k = nVar;
        l = h1.q(16.0d);
        m = h1.r(12);
        n = h1.q(0.4d);
        o = lVar2;
        p = nVar;
        q = h1.q(64.0d);
        r = h1.r(57);
        long jQ = h1.q(0.2d);
        androidx.compose.ui.unit.p[] pVarArr = androidx.compose.ui.unit.o.b;
        long j2 = jQ & 1095216660480L;
        if (j2 == 0) {
            androidx.compose.ui.unit.i.a("Cannot perform operation for Unspecified type.");
        }
        s = h1.u(-androidx.compose.ui.unit.o.c(jQ), j2);
        t = lVar2;
        u = nVar;
        v = h1.q(52.0d);
        w = h1.r(45);
        x = h1.q(0.0d);
        y = lVar2;
        z = nVar;
        A = h1.q(44.0d);
        B = h1.r(36);
        C = h1.q(0.0d);
        D = lVar2;
        E = nVar;
        F = h1.q(40.0d);
        G = h1.r(32);
        H = h1.q(0.0d);
        I = lVar2;
        J = nVar;
        K = h1.q(36.0d);
        L = h1.r(28);
        M = h1.q(0.0d);
        N = lVar2;
        O = nVar;
        P = h1.q(32.0d);
        Q = h1.r(24);
        R = h1.q(0.0d);
        S = lVar2;
        T = nVar;
        U = h1.q(20.0d);
        V = h1.r(14);
        W = h1.q(0.1d);
        androidx.compose.ui.text.font.l lVar3 = z.b;
        X = lVar3;
        Y = nVar;
        Z = h1.q(16.0d);
        a0 = h1.r(12);
        b0 = h1.q(0.5d);
        c0 = lVar3;
        d0 = nVar;
        e0 = h1.q(16.0d);
        f0 = h1.r(11);
        g0 = h1.q(0.5d);
        h0 = lVar3;
        i0 = nVar;
        j0 = h1.q(28.0d);
        k0 = h1.r(22);
        l0 = h1.q(0.0d);
        m0 = lVar2;
        n0 = nVar;
        o0 = h1.q(24.0d);
        p0 = h1.r(16);
        q0 = h1.q(0.2d);
        r0 = lVar3;
        s0 = nVar;
        t0 = h1.q(20.0d);
        u0 = h1.r(14);
        v0 = h1.q(0.1d);
        w0 = lVar3;
        x0 = nVar;
        y0 = h1.q(24.0d);
        z0 = h1.r(16);
        A0 = h1.q(0.15d);
        B0 = lVar3;
        C0 = nVar;
        D0 = h1.q(20.0d);
        E0 = h1.r(14);
        F0 = h1.q(0.25d);
        G0 = lVar3;
        H0 = nVar;
        I0 = h1.q(16.0d);
        J0 = h1.r(12);
        K0 = h1.q(0.4d);
        L0 = lVar3;
        M0 = nVar;
        N0 = h1.q(64.0d);
        O0 = h1.r(57);
        P0 = h1.r(0);
        Q0 = lVar3;
        R0 = nVar;
        S0 = h1.q(52.0d);
        T0 = h1.r(45);
        U0 = h1.r(0);
        V0 = lVar3;
        W0 = nVar;
        X0 = h1.q(44.0d);
        Y0 = h1.r(36);
        Z0 = h1.r(0);
        a1 = lVar3;
        b1 = nVar;
        c1 = h1.q(40.0d);
        d1 = h1.r(32);
        e1 = h1.r(0);
        f1 = lVar3;
        g1 = nVar;
        h1 = h1.q(36.0d);
        i1 = h1.r(28);
        j1 = h1.r(0);
        k1 = lVar3;
        l1 = nVar;
        m1 = h1.q(32.0d);
        n1 = h1.r(24);
        o1 = h1.r(0);
        p1 = lVar3;
        q1 = nVar;
        r1 = h1.q(20.0d);
        s1 = h1.r(14);
        t1 = h1.q(0.1d);
        androidx.compose.ui.text.font.l lVar4 = z.a;
        u1 = lVar4;
        v1 = nVar;
        w1 = h1.q(16.0d);
        x1 = h1.r(12);
        y1 = h1.q(0.5d);
        z1 = lVar4;
        A1 = nVar;
        B1 = h1.q(16.0d);
        C1 = h1.r(11);
        D1 = h1.q(0.5d);
        E1 = lVar4;
        F1 = nVar;
        G1 = h1.q(28.0d);
        H1 = h1.r(22);
        I1 = h1.r(0);
        J1 = lVar3;
        K1 = nVar;
        L1 = h1.q(24.0d);
        M1 = h1.r(16);
        N1 = h1.q(0.15d);
        O1 = lVar4;
        P1 = nVar;
        Q1 = h1.q(20.0d);
        R1 = h1.r(14);
        S1 = h1.q(0.1d);
        T1 = lVar4;
    }
}
