package androidx.compose.ui.input.key;

import com.app.mlounge.emulator.LibretroCore;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Token;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public abstract class a {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final /* synthetic */ int F = 0;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        c.a(0);
        c.a(1);
        c.a(2);
        c.a(3);
        a = c.a(4);
        c.a(259);
        b = c.a(260);
        c = c.a(261);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(262, 263, 280, 281, 282);
        c.a(283);
        c.a(5);
        c.a(6);
        d = c.a(19);
        e = c.a(20);
        f = c.a(21);
        g = c.a(22);
        h = c.a(23);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(268, 269, 270, 271, 24);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(25, 26, 27, 28, 7);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(8, 9, 10, 11, 12);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(13, 14, 15, 16, 81);
        c.a(69);
        c.a(17);
        c.a(70);
        c.a(18);
        i = c.a(29);
        c.a(30);
        j = c.a(31);
        c.a(32);
        c.a(33);
        c.a(34);
        c.a(35);
        k = c.a(36);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(37, 38, 39, 40, 41);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(42, 43, 44, 45, 46);
        c.a(47);
        c.a(48);
        c.a(49);
        l = c.a(50);
        c.a(51);
        m = c.a(52);
        n = c.a(53);
        o = c.a(54);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(55, 56, 57, 58, 59);
        c.a(60);
        p = c.a(61);
        q = c.a(62);
        c.a(63);
        c.a(64);
        c.a(65);
        r = c.a(66);
        s = c.a(67);
        t = c.a(Token.ASSIGN_MOD);
        u = c.a(Token.ASSIGN_DIV);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.ASSIGN_EXP, 114, Token.HOOK, Token.COLON, Token.OR);
        c.a(Token.AND);
        c.a(Token.INC);
        c.a(120);
        c.a(Token.DOT);
        v = c.a(Token.FUNCTION);
        w = c.a(Token.EXPORT);
        x = c.a(Token.IMPORT);
        y = c.a(277);
        z = c.a(278);
        A = c.a(279);
        c.a(68);
        c.a(71);
        c.a(72);
        c.a(76);
        B = c.a(73);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(74, 75, 77, 78, 79);
        c.a(80);
        c.a(82);
        c.a(83);
        c.a(84);
        C = c.a(92);
        D = c.a(93);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(94, 95, 96, 97, 98);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(99, 100, Token.ASSIGN_LOGICAL_OR, Token.ASSIGN_BITXOR, Token.ASSIGN_BITAND);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.ASSIGN_LOGICAL_AND, Token.ASSIGN_LSH, Token.ASSIGN_RSH, Token.ASSIGN_URSH, Token.ASSIGN_ADD);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.ASSIGN_SUB, 110, 188, 189, 190);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(191, 192, 193, 194, 195);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(196, 197, 198, 199, Context.VERSION_ES6);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(201, 202, 203, Token.IF, Token.DO);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.FOR, Token.BREAK, Token.CONTINUE, Token.VAR, Token.WITH);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.CATCH, Token.FINALLY, Token.VOID, 140, Token.EMPTY);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.COMPUTED_PROPERTY, Token.BLOCK, Token.LABEL, Token.TARGET, Token.LOOP);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.EXPR_VOID, Token.EXPR_RESULT, Token.JSR, 150, Token.TYPEOFNAME);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.USE_STACK, Token.SETPROP_OP, Token.SETELEM_OP, Token.LOCAL_BLOCK, Token.SET_REF_OP);
        c.a(Token.DOTDOT);
        c.a(Token.COLONCOLON);
        c.a(Token.XML);
        E = c.a(160);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.XMLATTR, Token.XMLEND, Token.TO_OBJECT, Token.ELSE, 127);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(85, 86, 130, 87, 88);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(89, 90, 128, 222, Token.DEFAULT);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(226, LibretroCore.PSP_SCREEN_HEIGHT, 273, 274, 275);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(91, Token.TO_DOUBLE, Token.GET, Token.SET, Token.LET);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.CONST, Token.SETCONST, 170, Token.ARRAYCOMP, Token.LETEXPR);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.WITHEXPR, Token.DEBUGGER, Token.COMMENT, Token.GENEXPR, Token.METHOD);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.ARROW, Token.YIELD_STAR, 180, Token.TEMPLATE_CHARS, Token.TEMPLATE_LITERAL_SUBST);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(Token.TAGGED_TEMPLATE_LITERAL, Token.DOTDOTDOT, 185, Token.QUESTION_DOT, Token.LAST_TOKEN);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(204, 205, 206, 207, 208);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(209, 210, 211, 212, 213);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(214, 215, 216, 217, 218);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(219, 220, 221, 223, LibretroCore.SCREEN_HEIGHT);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(276, 225, 229, 230, 231);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(232, 233, 234, 235, 236);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(237, 238, 239, 240, 241);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(242, 243, 244, 245, 246);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(247, 248, 249, Context.VERSION_ECMASCRIPT, 251);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(252, 253, 254, 255, LibretroCore.SCREEN_WIDTH);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(257, 258, 264, 265, 266);
        androidx.compose.runtime.external.kotlinx.collections.immutable.internal.c.r(267, 284, 285, 286, 287);
        c.a(288);
    }

    public static final boolean a(long j2, long j3) {
        return j2 == j3;
    }
}
