package androidx.compose.material3;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public final class n0 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public q W;
    public q X;
    public q Y;
    public a0 Z;
    public final long a;
    public w2 a0;
    public final long b;
    public a1 b0;
    public final long c;
    public l1 c0;
    public final long d;
    public p2 d0;
    public final long e;
    public k3 e0;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public n0(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.a, "onPrimary=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.b, "primaryContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        androidx.privacysandbox.ads.adservices.java.internal.a.A(j, "inversePrimary=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.e, "secondary=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.f, "onSecondary=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.g, "secondaryContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.h, "onSecondaryContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.i, "tertiary=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.j, "onTertiary=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.k, "tertiaryContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.l, "onTertiaryContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.m, "background=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.n, "onBackground=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.o, "surface=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.p, "onSurface=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.q, "surfaceVariant=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.r, "onSurfaceVariant=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.s, "surfaceTint=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.t, "inverseSurface=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.u, "inverseOnSurface=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.v, "error=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.w, "onError=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.x, "errorContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.y, "onErrorContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.z, "outline=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.A, "outlineVariant=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.B, "scrim=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.C, "surfaceBright=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.D, "surfaceDim=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.E, "surfaceContainer=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.F, "surfaceContainerHigh=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.G, "surfaceContainerHighest=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.H, "surfaceContainerLow=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.I, "surfaceContainerLowest=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.J, "primaryFixed=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.K, "primaryFixedDim=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.L, "onPrimaryFixed=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(j, "onPrimaryFixedVariant=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.N, "secondaryFixed=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.O, "secondaryFixedDim=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.P, "onSecondaryFixed=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.Q, "onSecondaryFixedVariant=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.R, "tertiaryFixed=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.S, "tertiaryFixedDim=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.T, "onTertiaryFixed=", sb);
        androidx.privacysandbox.ads.adservices.java.internal.a.A(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) androidx.compose.ui.graphics.t.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
