package com.google.android.gms.measurement.internal;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Parser;

/* JADX INFO: compiled from: r8-map-id-e67002de5a40c891c754bff9e68f2bf8edbc7d2191d59a60e5e311fc3b432df9 */
/* JADX INFO: loaded from: classes.dex */
public abstract class f0 {
    public static final e0 A;
    public static final e0 A0;
    public static final e0 B;
    public static final e0 B0;
    public static final e0 C;
    public static final e0 C0;
    public static final e0 D;
    public static final e0 D0;
    public static final e0 E;
    public static final e0 E0;
    public static final e0 F;
    public static final e0 F0;
    public static final e0 G;
    public static final e0 G0;
    public static final e0 H;
    public static final e0 H0;
    public static final e0 I;
    public static final e0 I0;
    public static final e0 J;
    public static final e0 J0;
    public static final e0 K;
    public static final e0 K0;
    public static final e0 L;
    public static final e0 L0;
    public static final e0 M;
    public static final e0 M0;
    public static final e0 N;
    public static final e0 N0;
    public static final e0 O;
    public static final e0 O0;
    public static final e0 P;
    public static final e0 P0;
    public static final e0 Q;
    public static final e0 Q0;
    public static final e0 R;
    public static final e0 R0;
    public static final e0 S;
    public static final e0 S0;
    public static final e0 T;
    public static final e0 T0;
    public static final e0 U;
    public static final e0 U0;
    public static final e0 V;
    public static final e0 V0;
    public static final e0 W;
    public static final e0 W0;
    public static final e0 X;
    public static final e0 X0;
    public static final e0 Y;
    public static final e0 Y0;
    public static final e0 Z;
    public static final e0 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final e0 a0;
    public static final e0 a1;
    public static final e0 b;
    public static final e0 b0;
    public static final e0 b1;
    public static final e0 c;
    public static final e0 c0;
    public static final e0 c1;
    public static final e0 d;
    public static final e0 d0;
    public static final e0 d1;
    public static final e0 e;
    public static final e0 e0;
    public static final e0 e1;
    public static final e0 f;
    public static final e0 f0;
    public static final e0 f1;
    public static final e0 g;
    public static final e0 g0;
    public static final e0 g1;
    public static final e0 h;
    public static final e0 h0;
    public static final e0 h1;
    public static final e0 i;
    public static final e0 i0;
    public static final e0 i1;
    public static final e0 j;
    public static final e0 j0;
    public static final e0 j1;
    public static final e0 k;
    public static final e0 k0;
    public static final e0 l;
    public static final e0 l0;
    public static final e0 m;
    public static final e0 m0;
    public static final e0 n;
    public static final e0 n0;
    public static final e0 o;
    public static final e0 o0;
    public static final e0 p;
    public static final e0 p0;
    public static final e0 q;
    public static final e0 q0;
    public static final e0 r;
    public static final e0 r0;
    public static final e0 s;
    public static final e0 s0;
    public static final e0 t;
    public static final e0 t0;
    public static final e0 u;
    public static final e0 u0;
    public static final e0 v;
    public static final e0 v0;
    public static final e0 w;
    public static final e0 w0;
    public static final e0 x;
    public static final e0 x0;
    public static final e0 y;
    public static final e0 y0;
    public static final e0 z;
    public static final e0 z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, y.S, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, com.google.firebase.heartbeatinfo.e.z, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, com.google.firebase.heartbeatinfo.e.D, false);
        e = a("measurement.config.cache_time", 86400000L, a0.y, false);
        f = a("measurement.config.url_scheme", "https", z.B, false);
        g = a("measurement.config.url_authority", "app-measurement.com", y.E, false);
        h = a("measurement.upload.max_bundles", 100, b0.G, false);
        Integer numValueOf = Integer.valueOf(Parser.ARGC_LIMIT);
        i = a("measurement.upload.max_batch_size", numValueOf, a0.J, false);
        j = a("measurement.upload.max_bundle_size", numValueOf, z.M, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, y.P, false);
        l = a("measurement.upload.max_events_per_day", 100000, b0.R, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, com.google.android.gms.common.internal.k.C, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, com.google.android.material.shape.f.C, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, com.google.firebase.heartbeatinfo.e.B, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, androidx.work.impl.model.f.B, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, com.google.android.gms.common.internal.k.D, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", com.google.android.material.shape.f.D, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", com.google.firebase.heartbeatinfo.e.C, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", androidx.work.impl.model.f.C, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", com.google.android.gms.common.internal.k.E, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, com.google.android.material.shape.f.E, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, androidx.work.impl.model.f.D, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, com.google.android.gms.common.internal.k.F, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, com.google.android.material.shape.f.F, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, com.google.firebase.heartbeatinfo.e.E, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, okio.internal.g.e, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, org.schabi.newpipe.extractor.utils.a.e, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, com.google.android.material.shape.f.G, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, com.google.firebase.heartbeatinfo.e.F, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, y.y, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, z.y, false);
        G = a("measurement.upload.backoff_period", 43200000L, b0.y, false);
        a("measurement.upload.window_interval", 3600000L, y.z, false);
        H = a("measurement.upload.interval", 3600000L, z.z, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, a0.z, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, b0.z, false);
        K = a("measurement.upload.minimum_delay", 500L, y.A, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, z.A, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, a0.A, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, b0.A, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, y.B, false);
        P = a("measurement.upload.retry_time", 1800000L, a0.B, false);
        Q = a("measurement.upload.retry_count", 6, b0.B, false);
        R = a("measurement.upload.max_queue_time", 518400000L, y.C, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, z.C, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, a0.C, false);
        U = a("measurement.audience.filter_result_max_count", Integer.valueOf(Context.VERSION_ES6), b0.C, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, y.D, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, z.D, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, a0.D, false);
        b0 = a("measurement.test.test_string_flag", "---", b0.D, false);
        c0 = a("measurement.test.test_long_flag", -1L, z.E, false);
        a("measurement.test.test_cached_long_flag", -1L, a0.E, true);
        d0 = a("measurement.test.test_int_flag", -2, b0.E, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), y.F, false);
        a("measurement.experiment.max_ids", 50, z.F, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, a0.F, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, b0.F, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, y.G, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, z.G, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, a0.G, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, y.H, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, z.H, false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", a0.H, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", b0.H, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", y.I, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, z.I, false);
        q0 = a("measurement.rb.attribution.app_allowlist", "", a0.I, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", b0.I, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", y.J, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", z.J, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, b0.J, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, y.K, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, z.K, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, a0.K, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, b0.K, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, y.L, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, z.L, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, a0.L, false);
        a("measurement.config.default_flag_values", bool2, b0.L, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, y.M, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, a0.M, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, b0.M, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, y.N, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, z.N, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, a0.N, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, b0.N, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, y.O, false);
        K0 = a("measurement.service.store_null_safelist", bool2, z.O, false);
        L0 = a("measurement.service.store_safelist", bool2, a0.O, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, b0.O, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, z.P, true);
        O0 = a("measurement.rb.attribution.service", bool2, a0.P, true);
        P0 = a("measurement.rb.attribution.client2", bool2, b0.P, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, y.Q, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, z.Q, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, z.T, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, a0.Q, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, b0.Q, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, y.R, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, z.R, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, a0.R, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, com.google.firebase.heartbeatinfo.e.y, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, com.google.android.material.shape.f.z, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, com.google.android.material.shape.f.A, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, a0.S, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, z.S, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", androidx.work.impl.model.f.z, false);
        c1 = a("measurement.edpb.service", bool, com.google.android.gms.common.internal.k.A, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", com.google.android.gms.common.internal.k.B, false);
        e1 = a("measurement.robust_time_source_2", bool, y.T, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, b0.S, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", "", com.google.android.material.shape.f.B, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", "", com.google.firebase.heartbeatinfo.e.A, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", "", androidx.work.impl.model.f.A, false);
        j1 = a("measurement.diagnostics.enabled", bool, androidx.work.impl.model.f.y, false);
    }

    public static e0 a(String str, Object obj, w wVar, boolean z2) {
        e0 e0Var = new e0(str, obj, wVar);
        if (z2) {
            a.add(e0Var);
        }
        return e0Var;
    }
}
