package com.google.android.gms.measurement.internal;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Parser;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public abstract class h0 {
    public static final g0 A;
    public static final g0 A0;
    public static final g0 B;
    public static final g0 B0;
    public static final g0 C;
    public static final g0 C0;
    public static final g0 D;
    public static final g0 D0;
    public static final g0 E;
    public static final g0 E0;
    public static final g0 F;
    public static final g0 F0;
    public static final g0 G;
    public static final g0 G0;
    public static final g0 H;
    public static final g0 H0;
    public static final g0 I;
    public static final g0 I0;
    public static final g0 J;
    public static final g0 J0;
    public static final g0 K;
    public static final g0 K0;
    public static final g0 L;
    public static final g0 L0;
    public static final g0 M;
    public static final g0 M0;
    public static final g0 N;
    public static final g0 N0;
    public static final g0 O;
    public static final g0 O0;
    public static final g0 P;
    public static final g0 P0;
    public static final g0 Q;
    public static final g0 Q0;
    public static final g0 R;
    public static final g0 R0;
    public static final g0 S;
    public static final g0 S0;
    public static final g0 T;
    public static final g0 T0;
    public static final g0 U;
    public static final g0 U0;
    public static final g0 V;
    public static final g0 V0;
    public static final g0 W;
    public static final g0 W0;
    public static final g0 X;
    public static final g0 X0;
    public static final g0 Y;
    public static final g0 Y0;
    public static final g0 Z;
    public static final g0 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final g0 a0;
    public static final g0 a1;
    public static final g0 b;
    public static final g0 b0;
    public static final g0 b1;
    public static final g0 c;
    public static final g0 c0;
    public static final g0 c1;
    public static final g0 d;
    public static final g0 d0;
    public static final g0 d1;
    public static final g0 e;
    public static final g0 e0;
    public static final g0 e1;
    public static final g0 f;
    public static final g0 f0;
    public static final g0 f1;
    public static final g0 g;
    public static final g0 g0;
    public static final g0 g1;
    public static final g0 h;
    public static final g0 h0;
    public static final g0 h1;
    public static final g0 i;
    public static final g0 i0;
    public static final g0 i1;
    public static final g0 j;
    public static final g0 j0;
    public static final g0 j1;
    public static final g0 k;
    public static final g0 k0;
    public static final g0 l;
    public static final g0 l0;
    public static final g0 m;
    public static final g0 m0;
    public static final g0 n;
    public static final g0 n0;
    public static final g0 o;
    public static final g0 o0;
    public static final g0 p;
    public static final g0 p0;
    public static final g0 q;
    public static final g0 q0;
    public static final g0 r;
    public static final g0 r0;
    public static final g0 s;
    public static final g0 s0;
    public static final g0 t;
    public static final g0 t0;
    public static final g0 u;
    public static final g0 u0;
    public static final g0 v;
    public static final g0 v0;
    public static final g0 w;
    public static final g0 w0;
    public static final g0 x;
    public static final g0 x0;
    public static final g0 y;
    public static final g0 y0;
    public static final g0 z;
    public static final g0 z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, f0.D, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, z.y, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, w.E, false);
        e = a("measurement.config.cache_time", 86400000L, z.H, false);
        f = a("measurement.config.url_scheme", "https", x.L, false);
        g = a("measurement.config.url_authority", "app-measurement.com", w.P, false);
        h = a("measurement.upload.max_bundles", 100, z.S, false);
        Integer numValueOf = Integer.valueOf(Parser.ARGC_LIMIT);
        i = a("measurement.upload.max_batch_size", numValueOf, x.W, false);
        j = a("measurement.upload.max_bundle_size", numValueOf, w.a0, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, f0.z, false);
        l = a("measurement.upload.max_events_per_day", 100000, e0.D, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, z.A, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, w.B, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, x.B, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, z.B, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, w.C, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", x.C, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", z.C, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", w.D, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", x.D, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, z.D, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, x.E, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, z.E, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, w.F, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, x.F, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, z.F, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, w.G, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, x.G, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, z.G, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, w.H, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, x.H, false);
        G = a("measurement.upload.backoff_period", 43200000L, w.I, false);
        a("measurement.upload.window_interval", 3600000L, x.I, false);
        H = a("measurement.upload.interval", 3600000L, z.I, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, w.J, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, x.J, false);
        K = a("measurement.upload.minimum_delay", 500L, z.J, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, w.K, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, x.K, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, z.K, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, w.L, false);
        P = a("measurement.upload.retry_time", 1800000L, z.L, false);
        Q = a("measurement.upload.retry_count", 6, w.M, false);
        R = a("measurement.upload.max_queue_time", 518400000L, x.M, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, z.M, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, w.N, false);
        U = a("measurement.audience.filter_result_max_count", Integer.valueOf(Context.VERSION_ES6), x.N, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, z.N, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, w.O, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, x.O, false);
        b0 = a("measurement.test.test_string_flag", "---", z.O, false);
        c0 = a("measurement.test.test_long_flag", -1L, x.P, false);
        a("measurement.test.test_cached_long_flag", -1L, z.P, true);
        d0 = a("measurement.test.test_int_flag", -2, w.Q, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), x.Q, false);
        a("measurement.experiment.max_ids", 50, z.Q, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, w.R, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, x.R, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, z.R, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, w.S, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, x.S, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, w.T, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, x.T, false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", z.T, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", w.U, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", x.U, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, z.U, false);
        q0 = a("measurement.rb.attribution.app_allowlist", "", w.V, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", x.V, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", z.V, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", w.W, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, z.W, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, w.X, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, x.X, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, z.X, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, w.Y, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, x.Y, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, z.Y, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, w.Z, false);
        a("measurement.config.default_flag_values", bool2, x.Z, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, z.Z, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, x.a0, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, z.a0, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, w.b0, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, x.b0, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, z.b0, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, c0.y, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, e0.y, false);
        K0 = a("measurement.service.store_null_safelist", bool2, f0.y, false);
        L0 = a("measurement.service.store_safelist", bool2, c0.z, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, e0.z, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, c0.A, true);
        O0 = a("measurement.rb.attribution.service", bool2, e0.A, true);
        P0 = a("measurement.rb.attribution.client2", bool2, f0.A, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, c0.B, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, e0.B, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, e0.F, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, f0.B, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, c0.C, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, e0.C, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, f0.C, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, c0.D, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, com.google.android.material.shape.g.e, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, com.google.android.gms.common.internal.k.z, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, x.y, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, e0.E, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, c0.E, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", w.z, false);
        c1 = a("measurement.edpb.service", bool, w.y, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", x.z, false);
        e1 = a("measurement.robust_time_source_2", bool, c0.F, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, f0.E, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", "", z.z, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", "", w.A, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", "", x.A, false);
        j1 = a("measurement.diagnostics.enabled", bool, com.google.firebase.heartbeatinfo.e.z, false);
    }

    public static g0 a(String str, Object obj, y yVar, boolean z2) {
        g0 g0Var = new g0(str, obj, yVar);
        if (z2) {
            a.add(g0Var);
        }
        return g0Var;
    }
}
