package androidx.constraintlayout.widget;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-b723831e8a75f5c253aef5210d8563f5ef31d2a2db903326935496738229b331 */
/* JADX INFO: loaded from: classes.dex */
public final class i {
    public int a;
    public final l b;
    public final k c;
    public final j d;
    public final m e;
    public HashMap f;

    public i() {
        l lVar = new l();
        lVar.a = 0;
        lVar.b = 0;
        lVar.c = 1.0f;
        lVar.d = Float.NaN;
        this.b = lVar;
        k kVar = new k();
        kVar.a = -1;
        kVar.b = 0;
        kVar.c = -1;
        kVar.d = Float.NaN;
        kVar.e = Float.NaN;
        kVar.f = Float.NaN;
        kVar.g = -1;
        kVar.h = null;
        kVar.i = -1;
        this.c = kVar;
        j jVar = new j();
        jVar.a = false;
        jVar.d = -1;
        jVar.e = -1;
        jVar.f = -1.0f;
        jVar.g = -1;
        jVar.h = -1;
        jVar.i = -1;
        jVar.j = -1;
        jVar.k = -1;
        jVar.l = -1;
        jVar.m = -1;
        jVar.n = -1;
        jVar.o = -1;
        jVar.p = -1;
        jVar.q = -1;
        jVar.r = -1;
        jVar.s = -1;
        jVar.t = -1;
        jVar.u = -1;
        jVar.v = 0.5f;
        jVar.w = 0.5f;
        jVar.x = null;
        jVar.y = -1;
        jVar.z = 0;
        jVar.A = 0.0f;
        jVar.B = -1;
        jVar.C = -1;
        jVar.D = -1;
        jVar.E = 0;
        jVar.F = 0;
        jVar.G = 0;
        jVar.H = 0;
        jVar.I = 0;
        jVar.J = 0;
        jVar.K = 0;
        jVar.L = Integer.MIN_VALUE;
        jVar.M = Integer.MIN_VALUE;
        jVar.N = Integer.MIN_VALUE;
        jVar.O = Integer.MIN_VALUE;
        jVar.P = Integer.MIN_VALUE;
        jVar.Q = Integer.MIN_VALUE;
        jVar.R = Integer.MIN_VALUE;
        jVar.S = -1.0f;
        jVar.T = -1.0f;
        jVar.U = 0;
        jVar.V = 0;
        jVar.W = 0;
        jVar.X = 0;
        jVar.Y = -1;
        jVar.Z = -1;
        jVar.a0 = -1;
        jVar.b0 = -1;
        jVar.c0 = 1.0f;
        jVar.d0 = 1.0f;
        jVar.e0 = -1;
        jVar.f0 = 0;
        jVar.g0 = -1;
        jVar.k0 = false;
        jVar.l0 = false;
        jVar.m0 = true;
        jVar.n0 = 0;
        this.d = jVar;
        m mVar = new m();
        mVar.a = 0.0f;
        mVar.b = 0.0f;
        mVar.c = 0.0f;
        mVar.d = 1.0f;
        mVar.e = 1.0f;
        mVar.f = Float.NaN;
        mVar.g = Float.NaN;
        mVar.h = -1;
        mVar.i = 0.0f;
        mVar.j = 0.0f;
        mVar.k = 0.0f;
        mVar.l = false;
        mVar.m = 0.0f;
        this.e = mVar;
        this.f = new HashMap();
    }

    public final void a(e eVar) {
        j jVar = this.d;
        eVar.d = jVar.g;
        eVar.e = jVar.h;
        eVar.f = jVar.i;
        eVar.g = jVar.j;
        eVar.h = jVar.k;
        eVar.i = jVar.l;
        eVar.j = jVar.m;
        eVar.k = jVar.n;
        eVar.l = jVar.o;
        eVar.m = jVar.p;
        eVar.n = jVar.q;
        eVar.r = jVar.r;
        eVar.s = jVar.s;
        eVar.t = jVar.t;
        eVar.u = jVar.u;
        ((ViewGroup.MarginLayoutParams) eVar).leftMargin = jVar.E;
        ((ViewGroup.MarginLayoutParams) eVar).rightMargin = jVar.F;
        ((ViewGroup.MarginLayoutParams) eVar).topMargin = jVar.G;
        ((ViewGroup.MarginLayoutParams) eVar).bottomMargin = jVar.H;
        eVar.z = jVar.Q;
        eVar.A = jVar.P;
        eVar.w = jVar.M;
        eVar.y = jVar.O;
        eVar.D = jVar.v;
        eVar.E = jVar.w;
        eVar.o = jVar.y;
        eVar.p = jVar.z;
        eVar.q = jVar.A;
        eVar.F = jVar.x;
        eVar.S = jVar.B;
        eVar.T = jVar.C;
        eVar.H = jVar.S;
        eVar.G = jVar.T;
        eVar.J = jVar.V;
        eVar.I = jVar.U;
        eVar.V = jVar.k0;
        eVar.W = jVar.l0;
        eVar.K = jVar.W;
        eVar.L = jVar.X;
        eVar.O = jVar.Y;
        eVar.P = jVar.Z;
        eVar.M = jVar.a0;
        eVar.N = jVar.b0;
        eVar.Q = jVar.c0;
        eVar.R = jVar.d0;
        eVar.U = jVar.D;
        eVar.c = jVar.f;
        eVar.a = jVar.d;
        eVar.b = jVar.e;
        ((ViewGroup.MarginLayoutParams) eVar).width = jVar.b;
        ((ViewGroup.MarginLayoutParams) eVar).height = jVar.c;
        String str = jVar.j0;
        if (str != null) {
            eVar.X = str;
        }
        eVar.Y = jVar.n0;
        eVar.setMarginStart(jVar.J);
        eVar.setMarginEnd(jVar.I);
        eVar.a();
    }

    public final Object clone() {
        i iVar = new i();
        j jVar = iVar.d;
        jVar.getClass();
        j jVar2 = this.d;
        jVar.a = jVar2.a;
        jVar.b = jVar2.b;
        jVar.c = jVar2.c;
        jVar.d = jVar2.d;
        jVar.e = jVar2.e;
        jVar.f = jVar2.f;
        jVar.g = jVar2.g;
        jVar.h = jVar2.h;
        jVar.i = jVar2.i;
        jVar.j = jVar2.j;
        jVar.k = jVar2.k;
        jVar.l = jVar2.l;
        jVar.m = jVar2.m;
        jVar.n = jVar2.n;
        jVar.o = jVar2.o;
        jVar.p = jVar2.p;
        jVar.q = jVar2.q;
        jVar.r = jVar2.r;
        jVar.s = jVar2.s;
        jVar.t = jVar2.t;
        jVar.u = jVar2.u;
        jVar.v = jVar2.v;
        jVar.w = jVar2.w;
        jVar.x = jVar2.x;
        jVar.y = jVar2.y;
        jVar.z = jVar2.z;
        jVar.A = jVar2.A;
        jVar.B = jVar2.B;
        jVar.C = jVar2.C;
        jVar.D = jVar2.D;
        jVar.E = jVar2.E;
        jVar.F = jVar2.F;
        jVar.G = jVar2.G;
        jVar.H = jVar2.H;
        jVar.I = jVar2.I;
        jVar.J = jVar2.J;
        jVar.K = jVar2.K;
        jVar.L = jVar2.L;
        jVar.M = jVar2.M;
        jVar.N = jVar2.N;
        jVar.O = jVar2.O;
        jVar.P = jVar2.P;
        jVar.Q = jVar2.Q;
        jVar.R = jVar2.R;
        jVar.S = jVar2.S;
        jVar.T = jVar2.T;
        jVar.U = jVar2.U;
        jVar.V = jVar2.V;
        jVar.W = jVar2.W;
        jVar.X = jVar2.X;
        jVar.Y = jVar2.Y;
        jVar.Z = jVar2.Z;
        jVar.a0 = jVar2.a0;
        jVar.b0 = jVar2.b0;
        jVar.c0 = jVar2.c0;
        jVar.d0 = jVar2.d0;
        jVar.e0 = jVar2.e0;
        jVar.f0 = jVar2.f0;
        jVar.g0 = jVar2.g0;
        jVar.j0 = jVar2.j0;
        int[] iArr = jVar2.h0;
        if (iArr != null) {
            jVar.h0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            jVar.h0 = null;
        }
        jVar.i0 = jVar2.i0;
        jVar.k0 = jVar2.k0;
        jVar.l0 = jVar2.l0;
        jVar.m0 = jVar2.m0;
        jVar.n0 = jVar2.n0;
        k kVar = iVar.c;
        kVar.getClass();
        k kVar2 = this.c;
        kVar2.getClass();
        kVar.a = kVar2.a;
        kVar.c = kVar2.c;
        kVar.e = kVar2.e;
        kVar.d = kVar2.d;
        l lVar = this.b;
        int i = lVar.a;
        l lVar2 = iVar.b;
        lVar2.a = i;
        lVar2.c = lVar.c;
        lVar2.d = lVar.d;
        lVar2.b = lVar.b;
        m mVar = iVar.e;
        mVar.getClass();
        m mVar2 = this.e;
        mVar2.getClass();
        mVar.a = mVar2.a;
        mVar.b = mVar2.b;
        mVar.c = mVar2.c;
        mVar.d = mVar2.d;
        mVar.e = mVar2.e;
        mVar.f = mVar2.f;
        mVar.g = mVar2.g;
        mVar.h = mVar2.h;
        mVar.i = mVar2.i;
        mVar.j = mVar2.j;
        mVar.k = mVar2.k;
        mVar.l = mVar2.l;
        mVar.m = mVar2.m;
        iVar.a = this.a;
        return iVar;
    }
}
